# Generated by Django 4.2.3 on 2023-07-26 13:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_alter_user_last_ready_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2023, 7, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('ack_time', models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('pull_time', models.IntegerField(default=0)),
                ('run_time', models.IntegerField(default=0)),
                ('total_time', models.IntegerField(default=0)),
                ('cost', models.FloatField(default=0.0)),
                ('finished', models.BooleanField(default=False)),
                ('corr_id', models.UUIDField(db_index=True, default=0)),
                ('response', models.TextField(default='')),
                ('provider', models.ForeignKey(limit_choices_to={'is_provider': True}, on_delete=django.db.models.deletion.CASCADE, to='profiles.user')),
            ],
        ),
    ]
