# Generated by Django 4.2.3 on 2023-07-14 22:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_provider', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('last_ready_signal', models.DateTimeField(default=datetime.datetime(2018, 7, 1, 0, 0, tzinfo=datetime.timezone.utc))),
                ('location', models.CharField(blank=True, max_length=30)),
                ('ram', models.IntegerField(default=0)),
                ('cpu', models.IntegerField(default=0)),
            ],
        ),
    ]
