# Generated by Django 4.2.3 on 2023-07-26 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_ready_signal',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
